# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sink.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sink.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nsink.proto\x12\nsink.proto\"G\n\x0bPollRequest\x12\x13\n\x0bschema_name\x18\x01 \x01(\t\x12\x12\n\ntable_name\x18\x02 \x01(\t\x12\x0f\n\x07\x62uckets\x18\x03 \x03(\x05\"6\n\x0cPollResponse\x12&\n\x07records\x18\x01 \x03(\x0b\x32\x15.sink.proto.RowRecord\">\n\x0e\x44\x61taCollection\x12\x17\n\x0f\x64\x61ta_collection\x18\x01 \x01(\t\x12\x13\n\x0b\x65vent_count\x18\x02 \x01(\x03\"\xae\x01\n\x13TransactionMetadata\x12-\n\x06status\x18\x01 \x01(\x0e\x32\x1d.sink.proto.TransactionStatus\x12\n\n\x02id\x18\x02 \x01(\t\x12\x13\n\x0b\x65vent_count\x18\x03 \x01(\x03\x12\x34\n\x10\x64\x61ta_collections\x18\x04 \x03(\x0b\x32\x1a.sink.proto.DataCollection\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\"\x1c\n\x0b\x43olumnValue\x12\r\n\x05value\x18\x01 \x01(\x0c\"3\n\x08RowValue\x12\'\n\x06values\x18\x01 \x03(\x0b\x32\x17.sink.proto.ColumnValue\"\xd7\x01\n\tRowRecord\x12$\n\x06\x62\x65\x66ore\x18\x01 \x01(\x0b\x32\x14.sink.proto.RowValue\x12#\n\x05\x61\x66ter\x18\x02 \x01(\x0b\x32\x14.sink.proto.RowValue\x12&\n\x06source\x18\x03 \x01(\x0b\x32\x16.sink.proto.SourceInfo\x12\x30\n\x0btransaction\x18\x04 \x01(\x0b\x32\x1b.sink.proto.TransactionInfo\x12%\n\x02op\x18\x05 \x01(\x0e\x32\x19.sink.proto.OperationType\"7\n\nSourceInfo\x12\n\n\x02\x64\x62\x18\x01 \x01(\t\x12\x0e\n\x06schema\x18\x02 \x01(\t\x12\r\n\x05table\x18\x03 \x01(\t\"Q\n\x0fTransactionInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0btotal_order\x18\x02 \x01(\x03\x12\x1d\n\x15\x64\x61ta_collection_order\x18\x03 \x01(\x03*\'\n\x11TransactionStatus\x12\t\n\x05\x42\x45GIN\x10\x00\x12\x07\n\x03\x45ND\x10\x01*A\n\rOperationType\x12\n\n\x06INSERT\x10\x00\x12\n\n\x06UPDATE\x10\x01\x12\n\n\x06\x44\x45LETE\x10\x02\x12\x0c\n\x08SNAPSHOT\x10\x03\x32W\n\x14PixelsPollingService\x12?\n\nPollEvents\x12\x17.sink.proto.PollRequest\x1a\x18.sink.proto.PollResponseB&\n\x17io.pixelsdb.pixels.sinkB\tSinkProtoP\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sink_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\027io.pixelsdb.pixels.sinkB\tSinkProtoP\000'
  _globals['_TRANSACTIONSTATUS']._serialized_start=837
  _globals['_TRANSACTIONSTATUS']._serialized_end=876
  _globals['_OPERATIONTYPE']._serialized_start=878
  _globals['_OPERATIONTYPE']._serialized_end=943
  _globals['_POLLREQUEST']._serialized_start=26
  _globals['_POLLREQUEST']._serialized_end=97
  _globals['_POLLRESPONSE']._serialized_start=99
  _globals['_POLLRESPONSE']._serialized_end=153
  _globals['_DATACOLLECTION']._serialized_start=155
  _globals['_DATACOLLECTION']._serialized_end=217
  _globals['_TRANSACTIONMETADATA']._serialized_start=220
  _globals['_TRANSACTIONMETADATA']._serialized_end=394
  _globals['_COLUMNVALUE']._serialized_start=396
  _globals['_COLUMNVALUE']._serialized_end=424
  _globals['_ROWVALUE']._serialized_start=426
  _globals['_ROWVALUE']._serialized_end=477
  _globals['_ROWRECORD']._serialized_start=480
  _globals['_ROWRECORD']._serialized_end=695
  _globals['_SOURCEINFO']._serialized_start=697
  _globals['_SOURCEINFO']._serialized_end=752
  _globals['_TRANSACTIONINFO']._serialized_start=754
  _globals['_TRANSACTIONINFO']._serialized_end=835
  _globals['_PIXELSPOLLINGSERVICE']._serialized_start=945
  _globals['_PIXELSPOLLINGSERVICE']._serialized_end=1032
# @@protoc_insertion_point(module_scope)
